---
title: "Untitled"
author: "John Markin"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}


library(dplyr)
library(ggplot2)
library(transformr)
library(gganimate)
library(ggthemes)
library(reshape2)
library(gifski)
theme_set( theme_dark())

datause <- read.csv("daly-rates-from-all-causes-by-age.csv")

ans <- c()
for (i in as.integer(levels(as.factor(datause[,3])))) {
 r <-  subset(datause , Year == i)
 ans <- rbind(ans,c("Year" = i, apply(r[,-c(1:3)], 2, sum ) ))
}
ans <- as.data.frame(ans)

s_data <- melt(ans, id="Year") 

anr <- ggplot(data=s_data,aes(x=Year, y=value, colour=variable)) + 
  geom_line( size =1 , alpha = 0.75 )+  
  scale_color_brewer(palette="Paired") +
  ggtitle("Age Trend Visualisation for DALY 1990 - 2019")  + 
  scale_y_continuous(name="DALYs", labels =
                       scales::comma) 

anr.animation = anr + 
  transition_reveal(Year) + view_follow( fixed_y = TRUE)

animate(anr.animation , height = 500 , width =800 ,fps =30 , duration = 10 ,
        end_pause = 60 ,res = 100)





```
```{r echo=FALSE, message=FALSE, warning=FALSE,fig.width = 9.5}
knitr::include_url("https://prod-useast-a.online.tableau.com/t/johnmarkin/views/Book1/Dashboard1?:origin=card_share_link&:embed=n",
                   height="500")
```
